//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerskinSimulation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeerskinSimulation.Resources.Events", typeof(Events).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged some skins while exporting..
        /// </summary>
        public static string DamagedSkinsWhileExporting {
            get {
                return ResourceManager.GetString("DamagedSkinsWhileExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found extra skins during the hunt!.
        /// </summary>
        public static string FoundExtraSkins {
            get {
                return ResourceManager.GetString("FoundExtraSkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Had to pay a fine for transport issues..
        /// </summary>
        public static string HadToPayFineTransportIssues {
            get {
                return ResourceManager.GetString("HadToPayFineTransportIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High demand increased the selling price..
        /// </summary>
        public static string HighDemandIncreasedPrice {
            get {
                return ResourceManager.GetString("HighDemandIncreasedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost some skins due to bad weather..
        /// </summary>
        public static string LostSkinsBadWeather {
            get {
                return ResourceManager.GetString("LostSkinsBadWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a bonus for quick transport..
        /// </summary>
        public static string ReceivedBonusQuickTransport {
            get {
                return ResourceManager.GetString("ReceivedBonusQuickTransport", resourceCulture);
            }
        }
    }
}
