//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerskinSimulation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeerskinSimulation.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer cannot afford the skins..
        /// </summary>
        public static string BuyerCannotAffordSkins {
            get {
                return ResourceManager.GetString("BuyerCannotAffordSkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunted skins:.
        /// </summary>
        public static string HuntedSkins {
            get {
                return ResourceManager.GetString("HuntedSkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunting.
        /// </summary>
        public static string HuntingActivityName {
            get {
                return ResourceManager.GetString("HuntingActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of packhorses. Choose between 1 and 5..
        /// </summary>
        public static string InvalidNumberOfPackhorses {
            get {
                return ResourceManager.GetString("InvalidNumberOfPackhorses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No skins to export..
        /// </summary>
        public static string NoSkinsToExport {
            get {
                return ResourceManager.GetString("NoSkinsToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No skins to sell..
        /// </summary>
        public static string NoSkinsToSell {
            get {
                return ResourceManager.GetString("NoSkinsToSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough money to export..
        /// </summary>
        public static string NotEnoughMoneyToExport {
            get {
                return ResourceManager.GetString("NotEnoughMoneyToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough money to hunt..
        /// </summary>
        public static string NotEnoughMoneyToHunt {
            get {
                return ResourceManager.GetString("NotEnoughMoneyToHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough skins to export..
        /// </summary>
        public static string NotEnoughSkinsToExport {
            get {
                return ResourceManager.GetString("NotEnoughSkinsToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough skins to sell..
        /// </summary>
        public static string NotEnoughSkinsToSell {
            get {
                return ResourceManager.GetString("NotEnoughSkinsToSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough skins to transport..
        /// </summary>
        public static string NotEnoughSkinsToTransport {
            get {
                return ResourceManager.GetString("NotEnoughSkinsToTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient cannot afford the skins..
        /// </summary>
        public static string RecipientCannotAffordSkins {
            get {
                return ResourceManager.GetString("RecipientCannotAffordSkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transported skins:.
        /// </summary>
        public static string TransportedSkins {
            get {
                return ResourceManager.GetString("TransportedSkins", resourceCulture);
            }
        }
    }
}
