//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerskinSimulation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeerskinSimulation.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer cannot afford the skins..
        /// </summary>
        public static string BuyerCannotAffordSkins {
            get {
                return ResourceManager.GetString("BuyerCannotAffordSkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the 1700s, millions of white-tail deerskins played a vital role in the colonial economy. These skins were skinned, scraped, and packed by hand, primarily by Native Americans and frontier settlers. They were then carried over mountains by horseback and transported to port by wagon. Once at the port, they were shipped across the Atlantic to European tanneries. In Europe, the deerskins were highly valued for their quality and used to produce fine leather goods, fueling a lucrative transatlantic trade..
        /// </summary>
        public static string DefaultStory {
            get {
                return ResourceManager.GetString("DefaultStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deerskin Economy Simulator.
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered {0} skins..
        /// </summary>
        public static string ForwardedSkins {
            get {
                return ResourceManager.GetString("ForwardedSkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired {0} skins..
        /// </summary>
        public static string HuntedSkins {
            get {
                return ResourceManager.GetString("HuntedSkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunting.
        /// </summary>
        public static string HuntingActivityName {
            get {
                return ResourceManager.GetString("HuntingActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of packhorses. Choose between 1 and 5..
        /// </summary>
        public static string InvalidNumberOfPackhorses {
            get {
                return ResourceManager.GetString("InvalidNumberOfPackhorses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No skins to export..
        /// </summary>
        public static string NoSkinsToExport {
            get {
                return ResourceManager.GetString("NoSkinsToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No skins to sell..
        /// </summary>
        public static string NoSkinsToSell {
            get {
                return ResourceManager.GetString("NoSkinsToSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough money to export..
        /// </summary>
        public static string NotEnoughMoneyToExport {
            get {
                return ResourceManager.GetString("NotEnoughMoneyToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough money to hunt..
        /// </summary>
        public static string NotEnoughMoneyToHunt {
            get {
                return ResourceManager.GetString("NotEnoughMoneyToHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough money to travel..
        /// </summary>
        public static string NotEnoughMoneyTravel {
            get {
                return ResourceManager.GetString("NotEnoughMoneyTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough skins to export..
        /// </summary>
        public static string NotEnoughSkinsToExport {
            get {
                return ResourceManager.GetString("NotEnoughSkinsToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough skins to sell..
        /// </summary>
        public static string NotEnoughSkinsToSell {
            get {
                return ResourceManager.GetString("NotEnoughSkinsToSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough skins to transport..
        /// </summary>
        public static string NotEnoughSkinsToTransport {
            get {
                return ResourceManager.GetString("NotEnoughSkinsToTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient cannot afford the skins..
        /// </summary>
        public static string RecipientCannotAffordSkins {
            get {
                return ResourceManager.GetString("RecipientCannotAffordSkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transported skins:.
        /// </summary>
        public static string TransportedSkins {
            get {
                return ResourceManager.GetString("TransportedSkins", resourceCulture);
            }
        }
    }
}
